package com.cellexperts.db.hbm;

// Generated Sep 3, 2015 2:22:26 PM by Hibernate Tools 3.4.0.CR1

/**
 * DailyTimesheetDtls generated by hbm2java
 */
public class DailyTimesheetDtls implements java.io.Serializable {

	private DailyTimesheetDtlsId id;
	private EmployeeTimesheet employeeTimesheet;
	private String day;
	private Long hours;
	private Long overtime;
	private Boolean leave;
	private String dailyTimesheetDtlscol;

	public DailyTimesheetDtls() {
	}

	public DailyTimesheetDtls(DailyTimesheetDtlsId id,
			EmployeeTimesheet employeeTimesheet) {
		this.id = id;
		this.employeeTimesheet = employeeTimesheet;
	}

	public DailyTimesheetDtls(DailyTimesheetDtlsId id,
			EmployeeTimesheet employeeTimesheet, String day, Long hours,
			Long overtime, Boolean leave, String dailyTimesheetDtlscol) {
		this.id = id;
		this.employeeTimesheet = employeeTimesheet;
		this.day = day;
		this.hours = hours;
		this.overtime = overtime;
		this.leave = leave;
		this.dailyTimesheetDtlscol = dailyTimesheetDtlscol;
	}

	public DailyTimesheetDtlsId getId() {
		return this.id;
	}

	public void setId(DailyTimesheetDtlsId id) {
		this.id = id;
	}

	public EmployeeTimesheet getEmployeeTimesheet() {
		return this.employeeTimesheet;
	}

	public void setEmployeeTimesheet(EmployeeTimesheet employeeTimesheet) {
		this.employeeTimesheet = employeeTimesheet;
	}

	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	public Long getHours() {
		return this.hours;
	}

	public void setHours(Long hours) {
		this.hours = hours;
	}

	public Long getOvertime() {
		return this.overtime;
	}

	public void setOvertime(Long overtime) {
		this.overtime = overtime;
	}

	public Boolean getLeave() {
		return this.leave;
	}

	public void setLeave(Boolean leave) {
		this.leave = leave;
	}

	public String getDailyTimesheetDtlscol() {
		return this.dailyTimesheetDtlscol;
	}

	public void setDailyTimesheetDtlscol(String dailyTimesheetDtlscol) {
		this.dailyTimesheetDtlscol = dailyTimesheetDtlscol;
	}

}
