package com.cellexperts.db.hbm;

// Generated Sep 3, 2015 2:22:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * EmployeeTimesheet generated by hbm2java
 */
public class EmployeeTimesheet implements java.io.Serializable {

	private EmployeeTimesheetId id;
	private Employees employees;
	private Boolean submitted;
	private String employeeTimesheetcol;
	private String employeeTimesheetcol1;
	private Set dailyTimesheetDtlses = new HashSet(0);

	public EmployeeTimesheet() {
	}

	public EmployeeTimesheet(EmployeeTimesheetId id, Employees employees) {
		this.id = id;
		this.employees = employees;
	}

	public EmployeeTimesheet(EmployeeTimesheetId id, Employees employees,
			Boolean submitted, String employeeTimesheetcol,
			String employeeTimesheetcol1, Set dailyTimesheetDtlses) {
		this.id = id;
		this.employees = employees;
		this.submitted = submitted;
		this.employeeTimesheetcol = employeeTimesheetcol;
		this.employeeTimesheetcol1 = employeeTimesheetcol1;
		this.dailyTimesheetDtlses = dailyTimesheetDtlses;
	}

	public EmployeeTimesheetId getId() {
		return this.id;
	}

	public void setId(EmployeeTimesheetId id) {
		this.id = id;
	}

	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	public Boolean getSubmitted() {
		return this.submitted;
	}

	public void setSubmitted(Boolean submitted) {
		this.submitted = submitted;
	}

	public String getEmployeeTimesheetcol() {
		return this.employeeTimesheetcol;
	}

	public void setEmployeeTimesheetcol(String employeeTimesheetcol) {
		this.employeeTimesheetcol = employeeTimesheetcol;
	}

	public String getEmployeeTimesheetcol1() {
		return this.employeeTimesheetcol1;
	}

	public void setEmployeeTimesheetcol1(String employeeTimesheetcol1) {
		this.employeeTimesheetcol1 = employeeTimesheetcol1;
	}

	public Set getDailyTimesheetDtlses() {
		return this.dailyTimesheetDtlses;
	}

	public void setDailyTimesheetDtlses(Set dailyTimesheetDtlses) {
		this.dailyTimesheetDtlses = dailyTimesheetDtlses;
	}

}
