package com.cellexperts.db.hbm;

// Generated Sep 9, 2015 10:52:46 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employees generated by hbm2java
 */
public class Employees implements java.io.Serializable {

	private Integer employeeId;
	private String firstName;
	private String lastName;
	private Date startDt;
	private Integer phone;
	private String email;
	private String endDt;
	private String address;
	private Set employeeTimesheets = new HashSet(0);
	private Set stores = new HashSet(0);

	public Employees() {
	}

	public Employees(String firstName, String lastName, Date startDt,
			Integer phone, String email, String endDt, String address,
			Set employeeTimesheets, Set stores) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.startDt = startDt;
		this.phone = phone;
		this.email = email;
		this.endDt = endDt;
		this.address = address;
		this.employeeTimesheets = employeeTimesheets;
		this.stores = stores;
	}

	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Date getStartDt() {
		return this.startDt;
	}

	public void setStartDt(Date startDt) {
		this.startDt = startDt;
	}

	public Integer getPhone() {
		return this.phone;
	}

	public void setPhone(Integer phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEndDt() {
		return this.endDt;
	}

	public void setEndDt(String endDt) {
		this.endDt = endDt;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Set getEmployeeTimesheets() {
		return this.employeeTimesheets;
	}

	public void setEmployeeTimesheets(Set employeeTimesheets) {
		this.employeeTimesheets = employeeTimesheets;
	}

	public Set getStores() {
		return this.stores;
	}

	public void setStores(Set stores) {
		this.stores = stores;
	}

}
