package com.cellexperts.db.hbm;

// Generated Sep 3, 2015 2:22:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Store generated by hbm2java
 */
public class Store implements java.io.Serializable {

	private Integer storeId;
	private String city;
	private String storeNm;
	private Set<Employees> employeeses = new HashSet<Employees>(0);

	public Store() {
	}

	public Store(String city, String storeNm, Set employeeses) {
		this.city = city;
		this.storeNm = storeNm;
		this.employeeses = employeeses;
	}

	public Integer getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Integer storeId) {
		this.storeId = storeId;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getStoreNm() {
		return this.storeNm;
	}

	public void setStoreNm(String storeNm) {
		this.storeNm = storeNm;
	}

	public Set getEmployeeses() {
		return this.employeeses;
	}

	public void setEmployeeses(Set employeeses) {
		this.employeeses = employeeses;
	}

}
